### ISSUE TITLE
About the used slice and annotations

### ISSUE THREAD

**Issue by 1170300714** [sherrydoge/TransLiver#1]
Thanks for your great work!

I have to questions for your method.

1. According to Sec. Exp in your main paper, there are 4820 slices from the 761 cases. So each cases have about 6 slices. But in my understanding, each CT volume should contain about 100-200 slices. So how did you manage to obtain such a small number of slices? Did you only select the slices that contain lesions? If so, where do the slices for the testing phase come from? (In principle, the test dataset should not use any annotations.)"
 2. What is the purpose of annotations for positional information? In the paper, it seems that annotations are not used as a supervisory signal for training the segmentation mask. I guess the role of annotations is just to identify which slices in the original CT images contain lesions?

I hope you can clarify my doubts.

**Comment by sherrydoge** [comment]
Thanks for your attention to our work. This study is about the classification of multi-phase liver lesions, so we suppose that the position of lesions are already obtained. We use the position labels to register and extract lesion slices. In realistic applications, the position of lesions can be obtained by detection/segmentation models and our pre-processing unit is designed for a better integration with it. In the future, hopefully, we will try to extend this work to an end-to-end liver cancer diagnosis model.

**Comment by 1170300714** [comment]
收到，感谢您的来件

**Comment by sherrydoge** [comment]
Since this issue has not been updated for 2 weeks, I close it.

**Comment by 1170300714** [comment]
收到，感谢您的来件
