### ISSUE TITLE
More Detail about README

### ISSUE THREAD

**Issue by hczyni** [sherrydoge/TransLiver#2]
I really like this project. Could you please provide a more detail about README? Thank you!

**Comment by sherrydoge** [comment]
Thanks for your attention. I do not know what details you mean in the issue. You can feel free to ask your specific questions here.

**Comment by hczyni** [comment]
Thank you very much for your attention and reply! I would love for you to add more details about the replicated project, such as data preparation, loading, directory hierarchy, order of project execution, and so on.

**Comment by sherrydoge** [comment]
We have provided the details in README. You can ask concrete questions for your replication, or else we have no idea how to solve your issue.

**Comment by hczyni** [comment]
> We have provided the details in README. You can ask concrete questions for your replication, or else we have no idea how to solve your issue.

Hello, developers! How did you get the affine used in res_train.py in this project? Can you provide it? Thank you!

**Comment by sherrydoge** [comment]
The affine is fixed in our dataset, so we can provide any file to read the affine. If your affine varies across different files, you might need extra process.

**Comment by sherrydoge** [comment]
Since this issue has not been updated for 2 weeks, I close it.

**Comment by sherrydoge** [comment]
Since this issue has not been updated for 2 weeks, I close it.
