### ISSUE TITLE
question about code!

### ISSUE THREAD

**Issue by ZHEGG** [sherrydoge/TransLiver#3]
https://github.com/sherrydoge/TransLiver/blob/3ea4ecefe06389b6c89e97dfcdeefbee4edd9086/classification/models/vit_timm.py#L360
Thanks for the nice code, but I have some questions about why the bottleneck in this code does not participate in pooling in subsequent classifications? Hope for your reply!!!

**Comment by sherrydoge** [comment]
Thanks for your attention and it's a nice question. It's easy to mix up the cross phase tokens with class token in ViT, which participates in pooling. The cross phase tokens are used to communicate between phases. They are copied before being input to layers of different phases, and after that, they are output with information of each phase. After the average operation, they conduct fused information, are concatenated with phase-specific tokens and are input to the next layer. You can see them as a 'bottleneck' between phases, and find details in chapter 2.4 of the paper.

**Comment by ZHEGG** [comment]
Thanks for your answers. I have some further questions regarding the number of bottlenecks and the setting about the number of fusion layers. If these hyperparameters influence the results?What are the primary considerations when setting these parameters? I look forward to your response!!!

**Comment by sherrydoge** [comment]
We follow the settings of previous paper on these hyperparameters. We also experimented them changed in a small range, and the results show negligible difference.

**Comment by ZHEGG** [comment]
I see, thank you!!!
