### ISSUE TITLE
About the lesion_slice_classes_organized.npy file

### ISSUE THREAD

**Issue by aa1234241** [sherrydoge/TransLiver#4]
Hello, first thank you very much for your great work.

During read the code, I found the lesion_slice_classes_organized.npy is needed in the dataset. Could you tell me what content does is file contains and in which format?

<img width="855" alt="Screen Shot 2024-01-10 at 2 32 51 PM" src="https://github.com/sherrydoge/TransLiver/assets/24704252/055e7b78-5e21-4e97-8483-7784f3aef8bb">

Also, could you share the GPU memory usage and total training time?

Many thanks again!

**Comment by sherrydoge** [comment]
This file contains the class labels. It's a npy file with a python dict, where the key is the lesion id and the value is its class. You can revise the convert_class() in datagenerator.py for your dataset.
In our experimental settings, we use ~10G memory in each card (4 cards totally) and ~4 hours to train.

**Comment by aa1234241** [comment]
Thank you very much for your quick reply.   I have another question about the pretrained weight. Could you kindly tell me how to load the weight of the cmt_small.pt?  In the code I only find the code for loading vit_small. <img width="1177" alt="Screen Shot 2024-01-10 at 9 58 05 PM" src="https://github.com/sherrydoge/TransLiver/assets/24704252/5f9090f6-242e-4c7e-b3c9-4b2536967d36">

**Comment by sherrydoge** [comment]
Please refer to [vit_timm.py](https://github.com/sherrydoge/TransLiver/blob/3d841d6e6af251f5291e0b25b09b2ecf5cf52d68/classification/models/vit_timm.py#L460-L501)

**Comment by aa1234241** [comment]
I see. Thank you.
